# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-17 04:36
from __future__ import unicode_literals

from django.conf import settings
import django.contrib.gis.db.models.fields
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Observation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entered', models.DateTimeField(auto_now_add=True)),
                ('values', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True)),
                ('observer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ObservationType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('icon', models.ImageField(upload_to='forms')),
                ('description', models.TextField()),
                ('html', models.TextField()),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Site',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('geometry', django.contrib.gis.db.models.fields.GeometryField(srid=4326)),
                ('accuracy', models.FloatField(blank=True, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='observation',
            name='site',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='obs.Site'),
        ),
        migrations.AddField(
            model_name='observation',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='obs.ObservationType'),
        ),
    ]
