# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-27 05:29
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('obs', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='observationtype',
            old_name='html',
            new_name='edit_html',
        ),
        migrations.AddField(
            model_name='observationtype',
            name='detail_html',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='observationtype',
            name='xlsform',
            field=models.FileField(blank=True, null=True, upload_to='forms'),
        ),
        migrations.AlterField(
            model_name='observationtype',
            name='edit_html',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='observationtype',
            name='form_json',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True),
        ),
    ]
